name: Build WinUI3 App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CONFIGURATION: 'Release'

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [x64]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore and Build
      run: |
        dotnet restore VocabApp\VocabApp.csproj -p:Platform=${{ matrix.platform }}
        dotnet build VocabApp\VocabApp.csproj -c ${{ env.CONFIGURATION }} -p:Platform=${{ matrix.platform }} --no-restore

    - name: Publish
      run: |
        dotnet publish VocabApp\VocabApp.csproj -c ${{ env.CONFIGURATION }} -p:Platform=${{ matrix.platform }} -p:WindowsPackageType=None -o publish\VocabApp-${{ matrix.platform }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VocabApp-${{ matrix.platform }}
        path: publish\VocabApp-${{ matrix.platform }}\**\*
        if-no-files-found: warn
        retention-days: 7
